#####################################################
################# EXPLANATION #######################
#
# This file and other configuration files are provided
# to create Hamilton specific functionality. While also
# providing interHamilton compatability for methods.
#
# This configuration file is used for deck loading.
# The Python script will read this file and, based
# on the volumes used for both plates and solutions,
# will autoload the deck for the Hamilton.
#
# This file is the lowest priority in the loading
# sequence. Thusly, this file is referenced when all 
# other deck loading protocols are exhausted.
#
#
#####################################################
#####################################################

VolumeEquations:
  200uL Biorad 96 Well PCR Plate:
    - SegmentNumber: 1
      MaxSegmentHeight: 0
      SegmentEquation: x * 2.3562
      
    - SegmentNumber: 2
      MaxSegmentHeight: 14.68
      SegmentEquation: x * 16.4934
  
  400uL Thermo 96 Well PCR Plate:
    - SegmentNumber: 1
      MaxSegmentHeight: 3
      SegmentEquation: x * 18.9150
      
    - SegmentNumber: 2
      MaxSegmentHeight: 8
      SegmentEquation: x * 56.7450

  1200uL DeepWell 96 Well PCR Plate:
    - SegmentNumber: 1
      MaxSegmentHeight: 3
      SegmentEquation: x * x * (13.1947 - (1.0472 * x))
      
    - SegmentNumber: 2
      MaxSegmentHeight: 18
      SegmentEquation: x * 70.5600

  2000uL Corning 96 Well PCR Plate:
    - SegmentNumber: 1
      MaxSegmentHeight: 4
      SegmentEquation: x * x * (12.5664 - (1.0472 * x))
      
    - SegmentNumber: 2
      MaxSegmentHeight: 38
      SegmentEquation: x * 64.0000


Dead Volume:
  200uL Biorad 96 Well PCR Plate: 10
  400uL Thermo 96 Well PCR Plate: 50
  1200uL DeepWell 96 Well PCR Plate: 50
  2000uL Corning 96 Well PCR Plate: 50
  200uL Starstedt Tube Plate: 25
  2000uL Starstedt Tube Plate: 150
  2000uL Water Total Recovery Vial Plate: 50
  Hamilton 1.5mL FlipTube: 150
  15mL Centrifuge Tube: 500
  60mL Reagent Reservior: 2500
  200mL Reagent Trough: 6000

Steps:
  Incubate:
    LidHomeSequences:
      - Lid1_Home
      - Lid2_Home
    Heaters:
      COM_ID:
        - 1
        - 2
      Type:
        - HeaterShaker
        - HeaterShaker
      Shake:
        - True
        - True
      SequencePrefix:
        - _HHS1_
        - _HHS2_
      PlateSequences:
        200uL Biorad 96 Well PCR Plate: 96WellPCRPlate200uL
        400uL Thermo 96 Well PCR Plate: 96WellPCRPlate400uL
        1200uL DeepWell 96 Well PCR Plate: 96WellPCRPlate1200uL
      LidSequences:  
        200uL Biorad 96 Well PCR Plate: Lid_200uL
        400uL Thermo 96 Well PCR Plate: Lid_400uL
        1200uL DeepWell 96 Well PCR Plate: Lid_1200uL

  Transport:
    Lid:
      Open: 88
      Close: 81
    Vacuum Manifold:
      Open: 97
      Close: 89
    200uL Biorad 96 Well PCR Plate:
      Open: 85
      Close: 75
    400uL Thermo 96 Well PCR Plate:
      Open: 85
      Close: 75
    1200uL DeepWell 96 Well PCR Plate:
      Open: 85
      Close: 73
    2000uL Corning 96 Well PCR Plate:
      Open: 85
      Close: 73

  Desalt:
    Preferred Loading:
      Waste: 
        - Carrier38_Pos1_96WellPCRPlate2000uL_1mLChannel
      Buffer: 
        - T4
      Destination: 
        - Carrier38_Pos5_96WellPCRPlate1200uL_1mLChannel
    Type:
      SizeX:
        100:
          Total Buffer Volume: 1000

  Vacuum:
      COM_ID: 1
      Home: _Vacuum_ManifoldHome
      Vacuum: _Vacuum_Manifold
      VacuumPlates:
        0.45um Self Poured ProA Plate:
          Sequnce: _Vacuum_SomePlateName
          Pressures:
            Low: 50
            Normal: 100
            High: 150
      PlateSequences:
        2000uL Corning 96 Well PCR Plate: _Vacuum_96WellPCRPlate2000uL
